name: ci

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FLUTTER_VERSION: 3.44.8

jobs:
  build:
    runs-on: windows-2022

    steps:

      # Checkout
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache Flutter
        uses: actions/cache@v4
        with:
          path: ~/flutter
          key: flutter-${{ env.FLUTTER_VERSION }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Setup Flutter (Mirror + Official Fallback)
      - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          $flutterDir = "$Env:USERPROFILE\flutter"
          if (Test-Path "$flutterDir\flutter\bin\flutter.bat") {
            "$flutterDir\flutter\bin" | Out-File -FilePath $Env:GITHUB_PATH -Append
            exit 0
          }
          Remove-Item $flutterDir -Recurse -Force -ErrorAction SilentlyContinue
          $zip = "$Env:USERPROFILE\flutter.zip"
          $official = "https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_${Env:FLUTTER_VERSION}-stable.zip"
          $mirror = "https://storage.flutter-io.cn/flutter_infra_release/releases/stable/windows/flutter_windows_${Env:FLUTTER_VERSION}-stable.zip"
          function Download($url) {
            Write-Host "Trying $url"
            try {
              Start-BitsTransfer -Source $url -Destination $zip
              return $true
            } catch {
              Write-Host "Failed: $url"
              return $false
            }
          }
          if (-not (Download $official)) {
            Write-Host "Official CDN failed, switching to mirror..."
            Download $mirror | Out-Null
          }
          if (-not (Test-Path $zip)) {
            throw "Flutter download failed from all sources."
          }
          Expand-Archive $zip -DestinationPath $flutterDir -Force
          Remove-Item $zip
          "$flutterDir\flutter\bin" | Out-File -FilePath $Env:GITHUB_PATH -Append
      # Verify
      - name: Verify Flutter & Dart
        run: |
          flutter doctor -v
          flutter --version
          dart --version
      # Pub Get
      - name: Flutter pub get
        run: flutter pub get


      # Build Windows
      - name: Build Windows
        run: flutter build windows --release


      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: hikari_windows
          path: build/windows/x64/runner/Release/


      # Android signing
      - name: Setup Android signing
        shell: pwsh
        run: |
          $keystorePath = "android/app/hikari-release.jks"
          [IO.File]::WriteAllBytes(
            $keystorePath,
            [Convert]::FromBase64String(
              "${{ secrets.KEYSTORE_BASE64 }}"
            )
          )
          Set-Content -Path android/key.properties -Value @(
            "storePassword=${{ secrets.KEYSTORE_PASSWORD }}"
            "keyPassword=${{ secrets.KEY_PASSWORD }}"
            "keyAlias=${{ secrets.KEY_ALIAS }}"
            "storeFile=hikari-release.jks"
          ) -Encoding UTF8
          Write-Host "Checking signing files..."
          Get-Item android/app/hikari-release.jks
          Get-Content android/key.properties
      # Build Android
      - name: Build Android
        run: flutter build apk --release --target-platform android-arm64

      - name: Upload Android APK
        uses: actions/upload-artifact@v7
        with:
          name: hikari_arm64-v8a
          path: build/app/outputs/flutter-apk/app-release.apk
